<a href="https://colab.research.google.com/github/NITIN-RAHUL/Machine-learning/blob/main/Basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[1,2,3]
a.append(4)


In [ ]:
print(a)

[1, 2, 3, 4]


In [ ]:

print(a)
a.append(7)
a.clear()
print(a)


[1, 3, 4, 7, 7]
[]


In [ ]:
del a
print(a)

NameError: ignored

In [ ]:
b={"name":1,"age":15}
print(b)
b.update("roll",23)

{'name': 1, 'age': 15}


TypeError: ignored

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
b=np.arange(1,7)
print(b)

[1 2 3 4 5 6]


In [ ]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones((3,4,5,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
        

In [ ]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.full((3,3)," NITIN")

array([[' NITIN', ' NITIN', ' NITIN'],
       [' NITIN', ' NITIN', ' NITIN'],
       [' NITIN', ' NITIN', ' NITIN']], dtype='<U6')

In [ ]:
np.linspace(0,1,num=5)#linspace divide the range for given number


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.arange(10,50,5)#arange is used for increment by number


array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
d=np.array([1,2,3,4,5,6,7])
print(d)

[1 2 3 4 5 6 7]


In [ ]:
d=np.array([[1,2],[4,5]])
print(d)

[[1 2]
 [4 5]]


In [ ]:
print(d[0:1,0])

[1]


In [ ]:
print(d)

[[1 2]
 [4 5]]


In [ ]:
print(d[1,1])

5


In [ ]:
print(d[1:2,1])

[5]


In [ ]:
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=z[1:3,2:4]
b[0,0]=0
print(b)
z
#when we change subset b main matrix z value too changes


[[ 0  8]
 [11 12]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  0,  8],
       [ 9, 10, 11, 12]])

In [ ]:
r1=z[1,:]#only
r2=z[1:2,:]
r3=z[[1],:]
print(r1,r1.shape)
print(r2,r2.shape)
print(r3,r3.shape)

[5 6 0 8] (4,)
[[5 6 0 8]] (1, 4)
[[5 6 0 8]] (1, 4)


In [ ]:
 import numpy as np
 a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
b=np.array([0,1,2,1])
print(a[np.arange(4),b])
print(a[a>2])
print(np.argmax(a))
print(np.argmin(a))
print(np.sort(a))
print(np.argsort(a)[::-1])#when we use arg we get index value only

[ 1  6 11 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]
16
0
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [ ]:
b=np.array([0,1,2,1])
print(a[np.arange(4),b])
print(a[a>2])
print(np.max(a))
print(np.min(a))
print(np.sort(a))
print(np.sort(a)[::-1])#we get values
print()

[ 1  6 11 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]
16
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


<function print>

In [ ]:
a=np.array([[3,2,1],[6,5,4],[9,8,7]])
print(a)
a=np.sort(a,axis=1,kind="mergesort")#axis=1 coulm
print(a)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.max(a))

9


In [ ]:
print(a.T)#transpose of a matrix

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a=np.array([[1],[3],[4]])
print(a)
print(a.squeeze())#squeeze will remove the subsets
print(a.reshape(-1,1))#reshape will comes into its original shape

[[1]
 [3]
 [4]]
[1 3 4]
[[1]
 [3]
 [4]]
